### PR TITLE
Mention that matrix-is-tester requires Python 2

### PR DESCRIPTION
**Pull request by anoadragon453**
Or else people will be confused.

Now they'll just be angry instead :^)

### CODE REVIEW

**Comment by richvdh** [comment]
This feels like a bug we need to fix rather than document. I'm pretty annoyed if python2-isms got baked in despite my best efforts to get @dbkr to test it with python3.

**Comment by dbkr** [comment]
It should work with python3: I ran it in py3 and it was fine. Is there a particular py2ism you've found?

**Comment by anoadragon453** [comment]
I get an error complaining about importing `BaseHTTPServer`, which is located here:

https://github.com/matrix-org/matrix-is-tester/blob/91c00498c1e497148db7ffac3ca19a9b6446c368/matrix_is_tester/fakehs.py#L19

Similarly with `urlparse`, which was renamed to `urllib.parse` in Python 3:

https://github.com/matrix-org/matrix-is-tester/blob/91c00498c1e497148db7ffac3ca19a9b6446c368/matrix_is_tester/fakehs.py#L24

**Comment by dbkr** [comment]
well boo :( 'written in python 2' might be a bit harsh if it's just those two though

**Comment by richvdh** [comment]
indeed. aren't those instances easily fixed?

**Comment by anoadragon453** [comment]
It may be more, that's just the first thing it dies on.

But I can try to fix and make a PR.

**Pull request closed without merging**
